### ISSUE TITLE
Tracker: v9 port

### ISSUE THREAD

**Issue by donmccurdy** [visgl/deck.gl-community#33]
## v9

- [ ] Get all examples passing and migrated to TypeScript
    - [x] https://github.com/visgl/deck.gl-community/issues/15
    - [ ] https://github.com/visgl/deck.gl-community/issues/38
    - [ ] fix 'graph-layers' examples
    - [ ] add 'layers' examples
    - [x] Add `@deck.gl-community/editable-layers` to example dependencies after it's published
    https://github.com/visgl/deck.gl-community/pull/63
- [x] Update `modules/*` to build against deck.gl v9
- [x] Get all unit tests passing (with Jest-style syntax, Deck v9, and TypeScript)
- [x] Migrate `modules/*` to TypeScript
    - [x] https://github.com/visgl/deck.gl-community/issues/14
- [x] Update `modules/*/test/*` to Jest-style tests
    - Could use Jest, Vitest, or Bun as the test runner. Consider options and make a decision. Vitest seems more batteries-included and ESM-friendly than Jest, where [ESM is experimental](https://jestjs.io/docs/ecmascript-modules). No opinion on Bun yet.
    - https://github.com/visgl/deck.gl-community/pull/41
    - https://github.com/visgl/deck.gl-community/pull/42
    - https://github.com/visgl/deck.gl-community/pull/45
    - https://github.com/visgl/deck.gl-community/pull/46
- [x] Fix ESLint and TSC errors and warnings as practical
    - https://github.com/visgl/deck.gl-community/pull/53
    - https://github.com/visgl/deck.gl-community/pull/54
    - https://github.com/visgl/deck.gl-community/pull/55
    - https://github.com/visgl/deck.gl-community/pull/64

**Comment by donmccurdy** [comment]
All modules are now passing tests against deck.gl v9. But note that the graph layers still use some deck v8 features (not covered by tests) and the examples do not work yet, so there is some remaining migration work for deck.gl v9 required there.

**Comment by ibgreen** [comment]
Moving the few remaining items into per-module trackers.
