### ISSUE TITLE
Tracker: editable-layers module

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl-community#38]
## Wishlist

- Goal: allow editable layers to be used with non-geospatial coordinates
- Goal: make this a generic layer pack (non-geo-speficic).
- Goal: Expose edit modes through Widgets somehow.

## v9.3 

- **High level**
  - [x] Docs - make sure the docs get the reader up to speed on the right things.
  - [x] `MeshLayer` - is it still needed? Docs says it should be [replaced](https://visgl.github.io/deck.gl-community/docs/modules/editable-layers/api-reference/layers/mesh-layer#lightsettings-object-optional)
  - [x] `Toolbox` React component - Could it be an `EditorLayer` composite layer with a suite of widgets?
- **examples** - Make all nebula.gl examples build again, or remove them
  - [x] editable-layers/sf (⚠️ renders, but throws errors)
  - [x] editable-layers/no-map
  - [x] editable-layers/getting-started
  - [x] editable-layers/codesandbox
  - [x] React 18, functional components, etc
- **Website** - 
  - [ ] editable-layers/editable-h3-cluster-layer
  - [x] editable-layers/sf (⚠️ renders, but throws errors)
  - [ ] editable-layers/overlays
  - [x] editable-layers/no-map
  - [x] editable-layers/getting-started
  - [x] editable-layers/codesandbox
 

## v9.0 - Initial forking from nebula.gl

 - [ ] **Website** - 
  - [x] Add `editor` example #76 @birkskyum 
  - [x] Add `advanced` example 
  - [ ] editable-layers/editable-h3-cluster-layer
  - [ ] editable-layers/sf (⚠️ renders, but throws errors)
  - [ ] editable-layers/overlays
  - [x] editable-layers/no-map
  - [x] editable-layers/getting-started
  - [x] editable-layers/codesandbox
- [ ] *examples** - Make all nebula.gl examples build again
  - [x] editable-layers/editor 
  - [x] editable-layers/advanced
  - [x] editable-layers/editable-h3-cluster-layer
  - [x] editable-layers/sf (⚠️ renders, but throws errors)
  - [ ] editable-layers/overlays
  - [x] editable-layers/no-map
  - [x] editable-layers/getting-started
  - [x] editable-layers/codesandbox
  - [x] Maplibre, token free basemaps, etc @birkskyum 
  - [x] React 18, functional components, etc
- [x] **Remove `@deck.gl-community/react-editable-layers`** #96 
  - [x] Create new react module `@deck.gl-community/react`
  - [x] Move independent react components from `@deck.gl-community/react-editable-layers` to `@deck.gl-community/react` @ibgreen 
  - [x] Move overlays to  `@deck.gl-community/react`
  - [x] Move EditorModal to `@deck.gl-community/react`
  - [x] Toolbox component - move to`editor` example.
- [x] **forking** 
  - [x] Add EditableGeojsonLayer & related code from nebula.g repo https://github.com/visgl/deck.gl-community/pull/37 @ibgreen 
  - [x] Apply the fixes needed for v9 EditableGeojsonLayer @donmccurdy 
  - [x] Publish package to npm
  - [x] Migrate tests to modern tooling @donmccurdy 
  - [x] Notify community in nebula.gl repo and slack channels @ibgreen 

## Background

[nebula.gl](https://nebula.gl) has become stale, and it is not possible to migrate it to deck.gl v9 easily. A number of project depend on it, in particular the `EditableGeojsonLayer`. In order to move forward, the code will be moved into this repo and published under a new npm package

**Comment by donmccurdy** [comment]
I'm working on updating the repo to v9 now. I'll start with the bing-maps module and example, migrating them to TypeScript at the same time.

**Comment by donmccurdy** [comment]
Progress on editable-layers:

https://github.com/visgl/deck.gl-community/pull/44

I've added a checkbox for each of the editable-layers examples to the OP above, some are now working, others still need to be ported.

**Comment by mariush2** [comment]
Hi, was unsure if I should create an issue for feature-requests or comment here. I saw in the history of the nebula.gl repo that the "MeasureDistance" mode for the "EditableGeoJson" layer was changed to only support multiple lengths being measured at once, instead of the user clicking two points only. Is this something that can be added, or is it something I could contribute with into this package?

**Comment by ibgreen** [comment]
@mariush2 We are still looking for volunteers to help maintain editable-layers, in the mean-time contributions are welcome. 

Please consider whether you can make the change without breaking existing apps or perhaps you need a new measurement mode.

**Comment by nipeone** [comment]
@ibgreen Hi, I migrated the issue from roadmap to here and deleted the original issue. Is there any plan to support brush mode? For example, create a large area with brush, or if  a closed area created with polygon is not satisfactory and you need to fix it with brush!

**Comment by ibgreen** [comment]
@nipeone Unfortunately, the editable-layers module doesn't have a named maintainer, so there is no one who can answer that. 

As you can see, the current roadmap is focused on just keeping the functionality alive and completing the fork from the stale nebula.gl repo.

There is a willingness to accept PRs if they are clean and simple and of course we'd warmly welcome anyone who wanted to help with maintenance.

**Comment by dm2x46** [comment]
Hi @ibgreen, do you have any plans to update the GeoJSON type for editable layers, similar to the GeoJSON type in deck.gl v9?

**Comment by ibgreen** [comment]
@dm2x46 Please ask questions in the GitHub discussions page. This is a tracker task for the module, not a discussion space.
