### ISSUE TITLE
Tracker: API Audit

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl-community#62]
Forking old repositories into this repo is just the first step. We need to review the APIs and make sure they are will consistent.

## v9

- [ ] editable-layers
  - [ ] `MeshLayer` - is it still needed? Docs says it should be [replaced](https://visgl.github.io/deck.gl-community/docs/modules/editable-layers/api-reference/layers/mesh-layer#lightsettings-object-optional)
- [ ] graph-layers
  - [ ] `MarkerLayer` seems very generic, including icon packing script
- [ ] react-editable-layers (goal: remove entire module)
  - [ ] Strip out non-graph specific react functionality
  - [x] Create new react module
  - [x] Move overlays to new react module
  - [x] Move EditorModal to new react module
  - [ ] ExportModal - is this still needed? can we just move into examples?
  - [ ] Toolbox component - is this needed? In that case shouldn't it be React independent? Could it be a widget?
- [ ] deckgl-react-graph-layers
  - [x]  Move button, viewport to generic react module
  - [ ] GraphGL component / hook is quite big - if so much helper code is needed, port to pureJS? Could it be a widget?

**Comment by ibgreen** [comment]
Tasks moved into per-module trackers.
