### ISSUE TITLE
Tracker: graph-layers module

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl-community#78]
## v9.1

- [ ] Audit
  - [ ] Rename modules to use `@deck.gl-community` prefix?

## v9.0

- [ ] **api and module structure**
  - [x] Move graph independent react components from `deck-react-graph-layers` to `@deck.gl-community/react`
  - [ ] Refactor graph helper code to be react independent and remove `deck-react-graph-layers` module.
- [ ] **examples** 
   - [ ] fix 'graph-layers' examples
   - [ ] modernize 'graph-layers' examples
   - [ ] Get all examples passing and migrated to TypeScript
 - [ ] **docs*
   - [ ] audit docs for correctness / completeness / freshness
 - [ ] **website**
   - [ ] Add examples to website.
