### ISSUE TITLE
Tracker: layers module

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl-community#80]
## v9.1

- [ ] Move generic layers from `editable-layers?
- [ ] Move generic layers from `graph-layers?

## v9.0

- [ ] Docs for `TileSourceLayer`?
- [ ] Example for `TileSourceLayer`?
- [ ] Docs for `DataDrivenTile3Dlayer`?
- [ ] Add example to website
